### ISSUE TITLE
Content-Type header should not be overridden

### ISSUE THREAD

**Issue by iamjamesim** [supabase-community/functions-swift#4]
# Bug report

## Describe the bug

`FunctionInvokeOptions` overrides the specified `Content-Type` header value to `application/octet-stream` when `body` is of type `Data`.

## To Reproduce

```
let boundary = "Boundary-\(UUID().uuidString)"
let contentType = "multipart/form-data; boundary=\(boundary)"
let options = FunctionInvokeOptions(
  headers: ["Content-Type": contentType],
  body: "binary value".data(using: .utf8)!
)
print(options.headers)
```
**Output**
```
["Content-Type": "application/octet-stream"]
```

## Expected behavior

Functions are invoked with the specified `Content-Type` header value.

## System Information

* `functions-swift`: `1.0.0`

## Additional context

I'm trying to invoke a function that handles multipart/form-data requests (based on [this example function](https://github.com/supabase/supabase/blob/master/examples/edge-functions/supabase/functions/file-upload-storage/index.ts)).

**Comment by iamjamesim** [comment]
I have a potential fix [here](https://github.com/iamjamesim/functions-swift/commit/50edb77ac6c5acef223d3f1932f13a4b1150a917). Happy to open a PR if it makes sense.

**Comment by grdsdev** [comment]
Hi @iamjamesim sorry for the late response. 

Feel free to PR your fix, it would be of great help.

**Comment by iamjamesim** [comment]
@grdsdev please take a look at the open PR when you get a chance. Just hoping to point my projects back to this repo instead of my fork. Thanks!

**Comment by grdsdev** [comment]
Release on https://github.com/supabase-community/functions-swift/releases/tag/1.1.1
